import type { ARSProvider } from '@/types/insurance';

export const ARS_PROVIDERS: ARSProvider[] = [
  {
    id: 'humano',
    name: 'ARS Humano',
    color: '#1D4ED8',
    plans: [
      {
        id: 'humano-max',
        name: 'Max',
        arsId: 'humano',
        coveragePercent: 90,
        maxCoverage: 500000,
        specialtyCoverage: {
          'medicina-general': 90,
          'cardiologia': 85,
          'pediatria': 90,
          'ginecologia': 90,
          'dermatologia': 80,
          'neurologia': 85,
          'ortopedia': 85,
        },
      },
      {
        id: 'humano-royal',
        name: 'Royal',
        arsId: 'humano',
        coveragePercent: 80,
        maxCoverage: 300000,
        specialtyCoverage: {
          'medicina-general': 80,
          'cardiologia': 75,
          'pediatria': 80,
          'ginecologia': 80,
          'dermatologia': 70,
          'neurologia': 75,
          'ortopedia': 75,
        },
      },
      {
        id: 'humano-mi-salud',
        name: 'Mi Salud',
        arsId: 'humano',
        coveragePercent: 70,
        maxCoverage: 150000,
        specialtyCoverage: {
          'medicina-general': 70,
          'cardiologia': 65,
          'pediatria': 70,
          'ginecologia': 70,
          'dermatologia': 60,
          'neurologia': 65,
          'ortopedia': 65,
        },
      },
    ],
  },
  {
    id: 'universal',
    name: 'Seguros Universal',
    color: '#0891B2',
    plans: [
      {
        id: 'universal-exclusivo',
        name: 'Exclusivo',
        arsId: 'universal',
        coveragePercent: 95,
        maxCoverage: 600000,
        specialtyCoverage: {
          'medicina-general': 95,
          'cardiologia': 90,
          'pediatria': 95,
          'ginecologia': 95,
          'dermatologia': 90,
          'neurologia': 90,
          'ortopedia': 90,
        },
      },
      {
        id: 'universal-platinum',
        name: 'Platinum',
        arsId: 'universal',
        coveragePercent: 85,
        maxCoverage: 400000,
        specialtyCoverage: {
          'medicina-general': 85,
          'cardiologia': 80,
          'pediatria': 85,
          'ginecologia': 85,
          'dermatologia': 80,
          'neurologia': 80,
          'ortopedia': 80,
        },
      },
      {
        id: 'universal-premium',
        name: 'Premium',
        arsId: 'universal',
        coveragePercent: 75,
        maxCoverage: 250000,
        specialtyCoverage: {
          'medicina-general': 75,
          'cardiologia': 70,
          'pediatria': 75,
          'ginecologia': 75,
          'dermatologia': 70,
          'neurologia': 70,
          'ortopedia': 70,
        },
      },
    ],
  },
  {
    id: 'mapfre',
    name: 'Mapfre Salud BHD',
    color: '#DC2626',
    plans: [
      {
        id: 'mapfre-salud-plus',
        name: 'Salud Plus',
        arsId: 'mapfre',
        coveragePercent: 88,
        maxCoverage: 450000,
        specialtyCoverage: {
          'medicina-general': 88,
          'cardiologia': 85,
          'pediatria': 88,
          'ginecologia': 88,
          'dermatologia': 82,
          'neurologia': 85,
          'ortopedia': 85,
        },
      },
      {
        id: 'mapfre-premium',
        name: 'Premium',
        arsId: 'mapfre',
        coveragePercent: 78,
        maxCoverage: 280000,
        specialtyCoverage: {
          'medicina-general': 78,
          'cardiologia': 75,
          'pediatria': 78,
          'ginecologia': 78,
          'dermatologia': 72,
          'neurologia': 75,
          'ortopedia': 75,
        },
      },
    ],
  },
  {
    id: 'constitucion',
    name: 'Constitución ARS',
    color: '#059669',
    plans: [
      {
        id: 'constitucion-basico',
        name: 'Básico',
        arsId: 'constitucion',
        coveragePercent: 70,
        maxCoverage: 200000,
        specialtyCoverage: {
          'medicina-general': 70,
          'cardiologia': 65,
          'pediatria': 70,
          'ginecologia': 70,
          'dermatologia': 60,
          'neurologia': 65,
          'ortopedia': 65,
        },
      },
      {
        id: 'constitucion-completo',
        name: 'Completo',
        arsId: 'constitucion',
        coveragePercent: 82,
        maxCoverage: 320000,
        specialtyCoverage: {
          'medicina-general': 82,
          'cardiologia': 78,
          'pediatria': 82,
          'ginecologia': 82,
          'dermatologia': 75,
          'neurologia': 78,
          'ortopedia': 78,
        },
      },
    ],
  },
  {
    id: 'leon-jimenes',
    name: 'ARS León Jimenes',
    color: '#7C3AED',
    plans: [
      {
        id: 'leon-salud',
        name: 'Salud Empresarial',
        arsId: 'leon-jimenes',
        coveragePercent: 85,
        maxCoverage: 380000,
        specialtyCoverage: {
          'medicina-general': 85,
          'cardiologia': 80,
          'pediatria': 85,
          'ginecologia': 85,
          'dermatologia': 78,
          'neurologia': 80,
          'ortopedia': 80,
        },
      },
    ],
  },
  {
    id: 'senasa',
    name: 'SeNaSa',
    color: '#0369A1',
    plans: [
      {
        id: 'senasa-contributivo',
        name: 'Contributivo',
        arsId: 'senasa',
        coveragePercent: 75,
        maxCoverage: 200000,
        specialtyCoverage: {
          'medicina-general': 75,
          'cardiologia': 70,
          'pediatria': 75,
          'ginecologia': 75,
          'dermatologia': 65,
          'neurologia': 70,
          'ortopedia': 70,
        },
      },
      {
        id: 'senasa-subsidiado',
        name: 'Subsidiado',
        arsId: 'senasa',
        coveragePercent: 90,
        maxCoverage: 100000,
        specialtyCoverage: {
          'medicina-general': 90,
          'cardiologia': 85,
          'pediatria': 90,
          'ginecologia': 90,
          'dermatologia': 80,
          'neurologia': 85,
          'ortopedia': 85,
        },
      },
      {
        id: 'senasa-voluntario',
        name: 'Voluntario',
        arsId: 'senasa',
        coveragePercent: 70,
        maxCoverage: 180000,
        specialtyCoverage: {
          'medicina-general': 70,
          'cardiologia': 65,
          'pediatria': 70,
          'ginecologia': 70,
          'dermatologia': 60,
          'neurologia': 65,
          'ortopedia': 65,
        },
      },
    ],
  },
  {
    id: 'reservas',
    name: 'ARS Reservas',
    color: '#92400E',
    plans: [
      {
        id: 'reservas-salud',
        name: 'Salud Reservas',
        arsId: 'reservas',
        coveragePercent: 80,
        maxCoverage: 280000,
        specialtyCoverage: {
          'medicina-general': 80,
          'cardiologia': 75,
          'pediatria': 80,
          'ginecologia': 80,
          'dermatologia': 72,
          'neurologia': 75,
          'ortopedia': 75,
        },
      },
    ],
  },
  {
    id: 'simag',
    name: 'SIMAG',
    color: '#0F766E',
    plans: [
      {
        id: 'simag-basico',
        name: 'Básico',
        arsId: 'simag',
        coveragePercent: 72,
        maxCoverage: 180000,
        specialtyCoverage: {
          'medicina-general': 72,
          'cardiologia': 68,
          'pediatria': 72,
          'ginecologia': 72,
          'dermatologia': 65,
          'neurologia': 68,
          'ortopedia': 68,
        },
      },
      {
        id: 'simag-plus',
        name: 'Plus',
        arsId: 'simag',
        coveragePercent: 83,
        maxCoverage: 300000,
        specialtyCoverage: {
          'medicina-general': 83,
          'cardiologia': 79,
          'pediatria': 83,
          'ginecologia': 83,
          'dermatologia': 76,
          'neurologia': 79,
          'ortopedia': 79,
        },
      },
    ],
  },
];

export function getARSById(id: string): ARSProvider | undefined {
  return ARS_PROVIDERS.find((a) => a.id === id);
}

export function getPlanById(arsId: string, planId: string) {
  const ars = getARSById(arsId);
  return ars?.plans.find((p) => p.id === planId);
}
