import type { Hospital } from '@/types/doctor';

export const HOSPITALS: Hospital[] = [
  // Hospitales Privados
  {
    id: 'clinica-abreu',
    name: 'Clínica Abreu',
    address: 'Av. Independencia 701',
    city: 'Santo Domingo',
    phone: '809-688-4411',
    type: 'private',
    specialties: ['medicina-general', 'cardiologia', 'ortopedia', 'ginecologia', 'pediatria'],
    coordinates: { lat: 18.4741, lng: -69.9312 },
  },
  {
    id: 'cedimat',
    name: 'CEDIMAT',
    address: 'Plaza de la Salud, Av. Ortega y Gasset',
    city: 'Santo Domingo',
    phone: '809-565-7878',
    type: 'private',
    specialties: ['cardiologia', 'neurologia', 'oncologia', 'medicina-general'],
    coordinates: { lat: 18.4832, lng: -69.9395 },
  },
  {
    id: 'plaza-de-la-salud',
    name: 'Plaza de la Salud',
    address: 'Av. Ortega y Gasset esq. Pepillo Salcedo',
    city: 'Santo Domingo',
    phone: '809-566-2444',
    type: 'private',
    specialties: ['medicina-general', 'pediatria', 'ginecologia', 'cardiologia', 'neurologia'],
    coordinates: { lat: 18.4830, lng: -69.9390 },
  },
  {
    id: 'corazones-unidos',
    name: 'Clínica Corazones Unidos',
    address: 'Av. Núñez de Cáceres 64',
    city: 'Santo Domingo',
    phone: '809-544-0000',
    type: 'private',
    specialties: ['cardiologia', 'medicina-general', 'cirugia'],
    coordinates: { lat: 18.4768, lng: -69.9221 },
  },
  {
    id: 'hospiten',
    name: 'Hospiten Santo Domingo',
    address: 'Av. Luperón esq. Pepillo Salcedo',
    city: 'Santo Domingo',
    phone: '809-541-3000',
    type: 'private',
    specialties: ['medicina-general', 'ginecologia', 'pediatria', 'traumatologia'],
    coordinates: { lat: 18.4855, lng: -69.9548 },
  },
  {
    id: 'union-medica-norte',
    name: 'Clínica Unión Médica del Norte',
    address: 'Av. 27 de Febrero 73',
    city: 'Santiago',
    phone: '809-575-0000',
    type: 'private',
    specialties: ['medicina-general', 'cardiologia', 'ortopedia', 'ginecologia'],
    coordinates: { lat: 19.4517, lng: -70.6970 },
  },
  {
    id: 'centro-medico-uce',
    name: 'Centro Médico UCE',
    address: 'Av. Máximo Gómez 72',
    city: 'Santo Domingo',
    phone: '809-221-0171',
    type: 'private',
    specialties: ['medicina-general', 'especialidades-varias'],
    coordinates: { lat: 18.4760, lng: -69.9180 },
  },
  {
    id: 'bournigal',
    name: 'Hospital Bournigal',
    address: 'Calle 16 de Agosto esq. Colón',
    city: 'Puerto Plata',
    phone: '809-586-2342',
    type: 'private',
    specialties: ['medicina-general', 'pediatria', 'ginecologia', 'cirugia'],
    coordinates: { lat: 19.7956, lng: -70.6891 },
  },
  {
    id: 'metropolitano-santiago',
    name: 'Hospital Metropolitano de Santiago',
    address: 'Av. Bartolomé Colón',
    city: 'Santiago',
    phone: '809-947-2222',
    type: 'private',
    specialties: ['medicina-general', 'cardiologia', 'neurologia', 'oncologia'],
    coordinates: { lat: 19.4512, lng: -70.6890 },
  },
  {
    id: 'clinica-esperanza',
    name: 'Clínica La Esperanza',
    address: 'Av. Independencia',
    city: 'Santo Domingo',
    phone: '809-685-0000',
    type: 'private',
    specialties: ['medicina-general', 'ginecologia', 'pediatria'],
    coordinates: { lat: 18.4720, lng: -69.9240 },
  },

  // Hospitales Públicos
  {
    id: 'dario-contreras',
    name: 'Hospital Universitario Dr. Darío Contreras',
    address: 'Av. Ortega y Gasset',
    city: 'Santo Domingo',
    phone: '809-566-1121',
    type: 'public',
    specialties: ['traumatologia', 'medicina-general', 'cirugia', 'ortopedia'],
    coordinates: { lat: 18.4860, lng: -69.9400 },
  },
  {
    id: 'robert-reid-cabral',
    name: 'Hospital Robert Reid Cabral',
    address: 'Av. Independencia esq. San Juan Bosco',
    city: 'Santo Domingo',
    phone: '809-689-6200',
    type: 'public',
    specialties: ['pediatria', 'neonatologia', 'cirugia-pediatrica'],
    coordinates: { lat: 18.4752, lng: -69.9291 },
  },
  {
    id: 'luis-e-aybar',
    name: 'Hospital Luis E. Aybar',
    address: 'Calle Luis E. Aybar, Gazcue',
    city: 'Santo Domingo',
    phone: '809-688-7281',
    type: 'public',
    specialties: ['medicina-general', 'ginecologia', 'cirugia'],
    coordinates: { lat: 18.4748, lng: -69.9323 },
  },
  {
    id: 'salvador-gautier',
    name: 'Hospital Salvador B. Gautier',
    address: 'Calle Pepillo Salcedo',
    city: 'Santo Domingo',
    phone: '809-540-0404',
    type: 'public',
    specialties: ['medicina-general', 'especialidades-varias'],
    coordinates: { lat: 18.4920, lng: -69.9560 },
  },
  {
    id: 'ney-arias',
    name: 'Hospital Traumatológico Ney Arias Lora',
    address: 'Av. Ortega y Gasset',
    city: 'Santo Domingo',
    phone: '809-563-5444',
    type: 'public',
    specialties: ['traumatologia', 'ortopedia', 'cirugia'],
    coordinates: { lat: 18.4870, lng: -69.9410 },
  },
  {
    id: 'ramon-de-lara',
    name: 'Hospital Militar Ramón de Lara',
    address: 'Av. 27 de Febrero',
    city: 'Santo Domingo',
    phone: '809-593-7077',
    type: 'public',
    specialties: ['medicina-general', 'cirugia', 'especialidades-varias'],
    coordinates: { lat: 18.4810, lng: -69.9190 },
  },
  {
    id: 'presidente-peynado',
    name: 'Hospital Policial Presidente Peynado',
    address: 'Av. Máximo Gómez',
    city: 'Santo Domingo',
    phone: '809-682-2171',
    type: 'public',
    specialties: ['medicina-general', 'especialidades-varias'],
    coordinates: { lat: 18.4755, lng: -69.9180 },
  },
  {
    id: 'maternidad-altagracia',
    name: 'Maternidad La Altagracia',
    address: 'Av. Tiradentes',
    city: 'Santo Domingo',
    phone: '809-565-4141',
    type: 'public',
    specialties: ['ginecologia', 'obstetricia', 'neonatologia'],
    coordinates: { lat: 18.4835, lng: -69.9360 },
  },

  // Centros Especializados
  {
    id: 'cecanot',
    name: 'CECANOT',
    address: 'Av. Tiradentes 65',
    city: 'Santo Domingo',
    phone: '809-540-4848',
    type: 'specialized',
    specialties: ['neurologia', 'neurocirugía'],
    coordinates: { lat: 18.4840, lng: -69.9380 },
  },
  {
    id: 'instituto-dermatologico',
    name: 'Instituto Dermatológico y Cirugía de Piel',
    address: 'Av. Pasteur, Gazcue',
    city: 'Santo Domingo',
    phone: '809-221-4946',
    type: 'specialized',
    specialties: ['dermatologia'],
    coordinates: { lat: 18.4763, lng: -69.9325 },
  },
  {
    id: 'incart',
    name: 'Instituto de Cardiología INCART',
    address: 'Av. San Martín',
    city: 'Santo Domingo',
    phone: '809-565-4333',
    type: 'specialized',
    specialties: ['cardiologia', 'cirugia-cardiovascular'],
    coordinates: { lat: 18.4850, lng: -69.9420 },
  },
  {
    id: 'idcp',
    name: 'IDCP',
    address: 'Av. Independencia',
    city: 'Santo Domingo',
    phone: '809-685-6500',
    type: 'specialized',
    specialties: ['cardiologia', 'medicina-general'],
    coordinates: { lat: 18.4735, lng: -69.9305 },
  },
  {
    id: 'centro-infantil',
    name: 'Centro Médico de Especialidades Infantiles',
    address: 'Av. Lincoln',
    city: 'Santo Domingo',
    phone: '809-544-3000',
    type: 'specialized',
    specialties: ['pediatria', 'neonatologia', 'cirugia-pediatrica'],
    coordinates: { lat: 18.4880, lng: -69.9350 },
  },
  {
    id: 'padre-billini',
    name: 'Hospital Padre Billini',
    address: 'Calle Santomé, Ciudad Colonial',
    city: 'Santo Domingo',
    phone: '809-221-8272',
    type: 'specialized',
    specialties: ['medicina-general', 'cirugia', 'pediatria'],
    coordinates: { lat: 18.4726, lng: -69.8905 },
  },
  {
    id: 'clinica-corominas',
    name: 'Clínica Corominas',
    address: 'Av. 27 de Febrero esq. Calle 5',
    city: 'Santo Domingo',
    phone: '809-542-2020',
    type: 'private',
    specialties: ['medicina-general', 'ginecologia', 'cirugia'],
    coordinates: { lat: 18.4820, lng: -69.9210 },
  },
  {
    id: 'clinica-san-francisco',
    name: 'Clínica San Francisco',
    address: 'Av. Francia',
    city: 'Santiago',
    phone: '809-582-0000',
    type: 'private',
    specialties: ['medicina-general', 'pediatria', 'ginecologia'],
    coordinates: { lat: 19.4480, lng: -70.7010 },
  },
  {
    id: 'clinica-independencia',
    name: 'Clínica Independencia',
    address: 'Av. Independencia 210',
    city: 'Santo Domingo',
    phone: '809-685-2500',
    type: 'private',
    specialties: ['medicina-general', 'especialidades-varias'],
    coordinates: { lat: 18.4760, lng: -69.9330 },
  },
  {
    id: 'clinica-abreu-santiago',
    name: 'Clínica Abreu Santiago',
    address: 'Av. Las Carreras',
    city: 'Santiago',
    phone: '809-582-2700',
    type: 'private',
    specialties: ['medicina-general', 'cardiologia', 'ortopedia'],
    coordinates: { lat: 19.4550, lng: -70.6920 },
  },
  {
    id: 'homs',
    name: 'HOMS (Hospital Oncológico)',
    address: 'Av. Máximo Gómez',
    city: 'Santo Domingo',
    phone: '809-227-0015',
    type: 'specialized',
    specialties: ['oncologia', 'radioterapia', 'quimioterapia'],
    coordinates: { lat: 18.4778, lng: -69.9168 },
  },
  {
    id: 'clinica-integral',
    name: 'Clínica Integral de La Romana',
    address: 'Calle Duarte 23',
    city: 'La Romana',
    phone: '809-556-2555',
    type: 'private',
    specialties: ['medicina-general', 'ginecologia', 'pediatria'],
    coordinates: { lat: 18.4273, lng: -68.9736 },
  },
];

export function getHospitalsByCity(city: string): Hospital[] {
  return HOSPITALS.filter((h) => h.city.toLowerCase() === city.toLowerCase());
}

export function getHospitalById(id: string): Hospital | undefined {
  return HOSPITALS.find((h) => h.id === id);
}
